namespace IntentSystem.Cli.Commands;

/// <summary>
/// G394: pure, deterministic protocol + classifier for review clarification
/// stops. Encodes the rule that a review loop must record current-PR blockers
/// durably ON the PR (an actionable blocker comment) before completing as
/// <c>request-update</c> or <c>clarification-required</c>, and that broader
/// future capabilities are split into follow-up issue/packet/signal work
/// rather than asked only in chat. Chat is not durable workflow state.
///
/// No I/O, no GitHub, no provider launch. Surfaced by
/// <see cref="GuideReviewCommand"/> as protocol rules, a blocker-comment
/// template, and worked routing examples (generated by
/// <see cref="Classify"/>), and exercised directly by unit tests.
/// </summary>
internal static class ReviewBlockerProtocol
{
    /// <summary>
    /// G394: the three durable-routing buckets a review blocker can fall into,
    /// plus <see cref="None"/> for "no durable blocker — proceed normally".
    /// </summary>
    public enum Category
    {
        /// <summary>No durable review blocker — normal approval / request-update flow applies.</summary>
        None,

        /// <summary>Fails a CURRENT-PR acceptance criterion: a durable PR blocker comment is mandatory.</summary>
        CurrentPrAcBlocker,

        /// <summary>Broader FUTURE capability gap that does not block the current PR's AC: route to follow-up issue/packet/signal.</summary>
        FollowUpCapabilityGap,

        /// <summary>Host metadata (<c>.intent-cli/**</c> / <c>intents/**</c>): never an implementation-PR comment (G287); structured operator stop.</summary>
        HostMetadataBlocker,
    }

    /// <summary>
    /// G394: the observable nature of a review blocker. The classifier is a
    /// pure function of these flags so guidance and tests agree.
    /// </summary>
    public readonly record struct Signal(
        bool FailsCurrentPrAcceptanceCriterion,
        bool TargetsHostMetadata,
        bool RequiresBroaderCapability,
        bool ImplementerCanFixOnPrBranch);

    /// <summary>
    /// G394: deterministic routing decision for a single review blocker.
    /// </summary>
    public sealed record Classification
    {
        public required Category Category { get; init; }

        /// <summary>A durable, actionable PR blocker comment must be posted before completing.</summary>
        public required bool RequiresDurablePrComment { get; init; }

        /// <summary>This finding must NOT be posted as an implementation-PR comment (G287 host-metadata).</summary>
        public required bool MustNotBePrComment { get; init; }

        /// <summary>A follow-up issue/packet/signal must be created and linked from the PR blocker comment.</summary>
        public required bool RequiresFollowUpIssue { get; init; }

        /// <summary>
        /// The recommended worker-complete outcome: <c>request-update</c>,
        /// <c>clarification-required</c>, <c>host-artifact-repair-required</c>,
        /// or <c>none</c>.
        /// </summary>
        public required string RecommendedOutcome { get; init; }

        public required string Rationale { get; init; }
    }

    public const string OutcomeRequestUpdate = "request-update";
    public const string OutcomeClarificationRequired = "clarification-required";
    public const string OutcomeHostArtifactRepairRequired = "host-artifact-repair-required";
    public const string OutcomeNone = "none";

    /// <summary>
    /// G394: classify a review blocker into its durable routing. Precedence:
    /// host-metadata (off-PR, G287) &gt; current-PR AC failure (mandatory PR
    /// blocker comment) &gt; broader follow-up capability. A current-PR AC
    /// blocker that is also operator/runtime-gated completes as
    /// <c>clarification-required</c> (not <c>request-update</c>) but still
    /// requires the durable PR comment first; if it is rooted in a broader
    /// capability, a follow-up issue/packet is also required and linked.
    /// </summary>
    public static Classification Classify(Signal signal)
    {
        // 1. Host metadata never becomes an implementation-PR review comment (G287).
        if (signal.TargetsHostMetadata)
        {
            return new Classification
            {
                Category = Category.HostMetadataBlocker,
                RequiresDurablePrComment = false,
                MustNotBePrComment = true,
                RequiresFollowUpIssue = false,
                RecommendedOutcome = OutcomeHostArtifactRepairRequired,
                Rationale =
                    "Blocker targets host metadata (.intent-cli/** or intents/**). It must be a structured "
                    + "operator stop / host-artifact repair, never an implementation-PR review comment (G287).",
            };
        }

        // 2. A current-PR acceptance-criterion failure ALWAYS needs a durable,
        //    actionable PR blocker comment before the loop completes. Whether
        //    that completion is request-update (implementer-fixable) or
        //    clarification-required (operator/runtime-gated) depends on who can
        //    unblock it; a broader capability root cause also needs a linked
        //    follow-up.
        if (signal.FailsCurrentPrAcceptanceCriterion)
        {
            var operatorGated = !signal.ImplementerCanFixOnPrBranch;
            var followUp = signal.RequiresBroaderCapability;
            var followUpClause = followUp
                ? " Link a follow-up issue/packet/signal for the broader capability from the PR blocker comment."
                : string.Empty;
            return new Classification
            {
                Category = Category.CurrentPrAcBlocker,
                RequiresDurablePrComment = true,
                MustNotBePrComment = false,
                RequiresFollowUpIssue = followUp,
                RecommendedOutcome = operatorGated ? OutcomeClarificationRequired : OutcomeRequestUpdate,
                Rationale = operatorGated
                    ? "Blocker fails a current-PR acceptance criterion and is operator/runtime-gated (not fixable on "
                      + "the PR branch). Post a durable PR blocker comment stating the failed AC, the evidence "
                      + "collected and why it is insufficient, the required unblock action, and what must NOT be "
                      + "claimed as collected; then complete as clarification-required (not chat-only)." + followUpClause
                    : "Blocker fails a current-PR acceptance criterion and is fixable on the PR branch. Post a durable "
                      + "PR blocker comment tying the finding to the failed AC, then complete as request-update." + followUpClause,
            };
        }

        // 3. A broader future capability that does NOT block the current PR's AC
        //    is follow-up issue/packet/signal work, not a chat question.
        if (signal.RequiresBroaderCapability)
        {
            return new Classification
            {
                Category = Category.FollowUpCapabilityGap,
                RequiresDurablePrComment = false,
                MustNotBePrComment = false,
                RequiresFollowUpIssue = true,
                RecommendedOutcome = OutcomeNone,
                Rationale =
                    "Broader future capability that does not block the current PR's acceptance criteria. Route it to a "
                    + "follow-up issue/packet/signal (not chat); link it from the PR if a related PR is open.",
            };
        }

        // 4. No durable blocker.
        return new Classification
        {
            Category = Category.None,
            RequiresDurablePrComment = false,
            MustNotBePrComment = false,
            RequiresFollowUpIssue = false,
            RecommendedOutcome = OutcomeNone,
            Rationale = "No durable review blocker detected; the normal approval / request-update flow applies.",
        };
    }

    /// <summary>
    /// G394: the durable-routing rules surfaced verbatim by
    /// <c>intent-cli guide review</c> so a reviewer records blockers on the PR
    /// instead of only in chat.
    /// </summary>
    public static readonly IReadOnlyList<string> ProtocolRules = new[]
    {
        "A blocker that fails a CURRENT-PR acceptance criterion MUST get a durable, actionable PR blocker comment "
            + "BEFORE the loop completes as request-update or clarification-required. Chat-only operator questions are "
            + "NOT durable workflow state and do not satisfy this requirement.",
        "Use a PR comment for a current-PR merge blocker; use a follow-up issue/packet/signal for a broader FUTURE "
            + "capability (e.g. synthetic touch automation or a reusable operator-supplied evidence workflow), and link "
            + "that follow-up from the PR blocker comment.",
        "A host-metadata blocker (.intent-cli/** or intents/**) is NEVER an implementation-PR review comment (G287); "
            + "surface it as a structured operator stop / host-artifact repair instead.",
        "An operator/runtime-gated evidence blocker completes as clarification-required, but only AFTER the durable PR "
            + "blocker comment is posted; the comment states what evidence is missing and what MUST NOT be claimed as "
            + "collected.",
        "clarification-required must leave enough durable PR context for the next wake/agent to know why the PR is "
            + "blocked; never reduce it to a chat-only question.",
        "Never fabricate operator-supplied or runtime/manual evidence, and never weaken an acceptance criterion to "
            + "approve evidence the packet forbids (e.g. scene-override capture standing in for a canonical-flow AC).",
    };

    /// <summary>
    /// G394: the required sections of a durable PR blocker comment, surfaced by
    /// <c>intent-cli guide review</c> as a fill-in template.
    /// </summary>
    public static readonly IReadOnlyList<string> BlockerCommentTemplateSections = new[]
    {
        "Failed acceptance criterion / packet goal — cite the exact AC or goal that is not satisfied.",
        "Current evidence and why it is insufficient — e.g. a `--scene Race.tscn` scene-override capture does not "
            + "satisfy a canonical Opening -> RaceSelection -> Race flow AC.",
        "Required unblock action — the concrete evidence or change that would satisfy the AC.",
        "False-claim boundaries — state explicitly what was NOT verified and must NOT be claimed as collected (no "
            + "fabricated runtime/manual evidence).",
        "Follow-up links — issue/packet/signal references for any broader capability gap, when applicable.",
    };

    /// <summary>
    /// G394: chat is not durable workflow state. Surfaced as an explicit signal
    /// so automation can quote it.
    /// </summary>
    public const bool ChatIsNotDurableWorkflowState = true;

    /// <summary>
    /// G394: worked routing examples rendered by <c>guide review</c> via
    /// <see cref="Classify"/>. The first mirrors the Zero4Racer PR #406 /
    /// Z4R-G201 AC#1 canonical-flow evidence blocker.
    /// </summary>
    public static readonly IReadOnlyList<(string Scenario, Signal Signal)> CanonicalScenarios = new[]
    {
        ("Current-PR AC fails because canonical-flow evidence is operator/runtime-gated and needs a broader capability "
            + "(Zero4Racer PR #406 / Z4R-G201 AC#1: scene-override capture is not the canonical Opening -> RaceSelection "
            + "-> Race flow)",
            new Signal(
                FailsCurrentPrAcceptanceCriterion: true,
                TargetsHostMetadata: false,
                RequiresBroaderCapability: true,
                ImplementerCanFixOnPrBranch: false)),
        ("Current-PR AC fails due to an implementer-fixable code/contract gap on the PR branch",
            new Signal(
                FailsCurrentPrAcceptanceCriterion: true,
                TargetsHostMetadata: false,
                RequiresBroaderCapability: false,
                ImplementerCanFixOnPrBranch: true)),
        ("Broader future capability that does NOT block the current PR's acceptance criteria",
            new Signal(
                FailsCurrentPrAcceptanceCriterion: false,
                TargetsHostMetadata: false,
                RequiresBroaderCapability: true,
                ImplementerCanFixOnPrBranch: false)),
        ("Host-metadata blocker (.intent-cli/** or intents/**)",
            new Signal(
                FailsCurrentPrAcceptanceCriterion: false,
                TargetsHostMetadata: true,
                RequiresBroaderCapability: false,
                ImplementerCanFixOnPrBranch: false)),
    };
}
