<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IntentSystem.Supervisor\IntentSystem.Supervisor.csproj" />
    <ProjectReference Include="..\IntentSystem.Projection\IntentSystem.Projection.csproj" />
  </ItemGroup>

</Project>
